name: (Prod) Update worker script

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  upload:
    runs-on: self-hosted

    steps:
      - name: Checkout actions
        uses: actions/checkout@v2

      - name: Publish script
        uses: cloudflare/wrangler-action@1.3.0
        with:
          environment: 'production'
          apiToken: ${{ secrets.CF_API_TOKEN }}
